### ISSUE TITLE
[qt_opencv_mingw.md] Вопросы

### ISSUE THREAD

**Issue by odimon21** [serykhelena/Guides#12]
Не происходит Компиляция на этапе Configure ?

при компиляции с параметрами Use default native compiler выходит ошибка 
![2](https://user-images.githubusercontent.com/41239838/67642100-74c3d300-f919-11e9-9633-37de512a05fe.png)

При выполнение пункта:
Если что-то идет не так - выбираем Specify native compilers и указываем пути:
С -> C:/Qt/Tools/mingw730_64/bin/gcc.exe
С++ -> C:/Qt/Tools/mingw730_64/bin/g++.exe
такая ошибка
![1](https://user-images.githubusercontent.com/41239838/67641824-79d35300-f916-11e9-8c51-87ee1417678f.png)

**Comment by odimon21** [comment]
в конце необходимо добавить библиотеку
 -lopencv_videoio347  \

**Comment by KaiL4eK** [comment]
Исправлено в f8e9a8d
