### ISSUE TITLE
[win/c_uc_recommend]: Выбор типа

### ISSUE THREAD

**Issue by PonomarevDA** [serykhelena/Guides#5]
В разделе [Выбор типа](https://github.com/serykhelena/Guides/blob/master/windows_os/c_uc_recommendations.md#%D0%B2%D1%8B%D0%B1%D0%BE%D1%80-%D1%82%D0%B8%D0%BF%D0%B0) я бы добавил еще, что для переносимости кода лучше использовать типы данных с явным указанием размера. Размер int'а не фиксируется стандартом (не говоря уже о том, что размер байта может быть разным).
Можно написать typedef'ы самому в каком-нибудь type.h, а могут они быть и уже написаны в каком-нибудь header'е. 
Пример typedef'ов:
```c++
typedef unsigned long long int uint64_t;
typedef signed long long int int64_t;  
typedef unsigned short int uint32_t;
typedef signed short int int32_t;
typedef unsigned short int uint16_t;
typedef signed short int int16_t;
typedef unsigned char uint8_t;
typedef signed char int8_t;
```
Также можно написать про least/fast типы.
- least'у соответствует минимальный доступный по размеру тип, который будет способен хранить указанное кол-во бит;
- fast'у соответствует максимальный по быстродействию тип, который будет способен хранить указанное кол-во бит.

При использовании типов данных, размер которых меньше длины машинного слова, может использоваться больше инструкций, что сказывается на производительности, поэтому иногда лучше использовать fast.

**Comment by KaiL4eK** [comment]
Идея отличная! В свою очередь, так как инструкция использовалась для студентов 4го курса, может стоит создать вторую часть с приставкой Advanced, как считаешь?

**Comment by KaiL4eK** [comment]
По поводу самостоятельных typedef я был бы осторожнее - такие вещи регламентируются библиотекой libc, поэтому стоит все таки использовать заголовок <stdint.h>.
Верно отмечено, что размеры в целом не регламентируются стандартами - в стандартах прописаны лишь зависимости размеров (больше или равно) разных типов, насколько я помню. Тип int - компиляторный, как и задающие размер типы, так что все таки рекомендую обращать внимание на определение внутри libc.

**Comment by PonomarevDA** [comment]
Думаю, что часть про least и fast типы все же стоит вынести в advanced, поскольку это уже касается проблемы оптимизации.
А вот объявление типов int без указания размера - это не очень хорошая практика, как мне кажется. Элементарно, могут возникнуть неприятности при переносе кода с одного контроллера на другой. Наверно, этому нужно отучать с самого начала.

По поводу самостоятельных typedef согласен :)

**Comment by KaiL4eK** [comment]
"А вот объявление типов int без указания размера - это не очень хорошая практика, как мне кажется. "
Асолютно поддерживаю, единственное не очень поминаю, где я за это ратовал)
Отучение на ранних стадиях тоже идея прекрасная, к сожалению отсутствие подготовки в программировании большинства студентов делает такого рода темы кошмаром, который тяжело усваивается, поэтому я буду думать как облегчить понимание, чтобы обязательно сообщить об этом студентам.
В любом случае начинать надо с методичек!
На самом деле типы `fast` и `least` я сам не очень пользую и они являются ооочень крутой оптимизацией, до которой делается еще ряд более простых шагов)
В любом случае, спасибо за комментарии! Очень приятно видеть чужие мнения со схожими идеями!
