### ISSUE TITLE
[win/c_uc_recommend]: Подключение модулей

### ISSUE THREAD

**Issue by PonomarevDA** [serykhelena/Guides#6]
На сколько я знаю, правильнее подключать заголовочные файлы по следующему принципу:
- Угловые скобки <> используются для подключения файлов, которые поставляются вместе с компилятором;
- Кавычки "" используются для подключения остальных файлов, например тех, которые мы написали сами и расположили в директории с исходным кодом.
Разница заключается лишь в том, в какой директории будет первым делом осуществляться поиск: в системных или в проекте. Таким образом, это влияет только на скорость сборки проекта.

В базовой части, думаю, стоит добавить, что файлы можно подключать двумя способами, и подключить semisegment.h правильно :)
А вот разницу между способами, можно добавить в Advanced.

**Comment by KaiL4eK** [comment]
Хотя я могу сильно ошибаться, так как [статья](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html) указывает на обратное по поводу понимания кавычек, видимо так отразилась собственная практика)
В любом случае, замечание имеет место быть, в свою очередь постараюсь учесть фикс при следующей итерации исправлений, спасибо!

**Comment by KaiL4eK** [comment]
И все таки, вот еще [статья](https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html), в ней грят о том, что `-I` добавляет путь к системным путям, что, похоже, требует от заголовка указания `<...>`, так как команда `cpp -v /dev/null -o /dev/null -I /home` дает следующий вывод:
```
...
#include "..." search starts here:
#include <...> search starts here:
 /home
 /usr/lib/gcc/x86_64-linux-gnu/5/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/5/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
...
```
