### ISSUE TITLE
[labs_design_eng.md] Оформление кода

### ISSUE THREAD

**Issue by serykhelena** [serykhelena/Guides#7]
Может быть добавить про оформление кода, что к функциям должны быть комментарии, или вообще можно оформлять в виде своих "библиотек"

**Comment by KaiL4eK** [comment]
Данная инструкция ориентирована на лабораторки по САУ, кода как такового тут нет, поэтому, думаю, будет лишнее. Есть мысль сделать инструкцию для предметов, где программирование применяется - может завести новый issue для этого в данной идеей?
